# Global SSH Options
ssh_options:
  :user: 'ubuntu'
  :keys: '/path/to/key'

# Global Server Defaults
server_defaults:
  :cloud: 'virtualbox'
  :provider: 'virtualbox'
  :private_key: '/path/to/key'
  :flavor: 'm1.small'
  :image_id: '4042220e-4f5e-4398-9054-39fbd75a5dd7'
  :keypair: 'home'
  :user: 'ubuntu'
  :security_groups: ['default', 'openstack']